// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdpKDqnyl0ha0ecfLhA-_XNwnhl0F65zA',
    appId: '1:106767773641:web:84de1fb981590994e2c218',
    messagingSenderId: '106767773641',
    projectId: 'linktab-3f36d',
    authDomain: 'linktab-3f36d.firebaseapp.com',
    storageBucket: 'linktab-3f36d.appspot.com',
    measurementId: 'G-222N363QTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADBjwWfCvHtCgwy2mupFDv8gE1J01IzA0',
    appId: '1:106767773641:android:906a990e0d66a86fe2c218',
    messagingSenderId: '106767773641',
    projectId: 'linktab-3f36d',
    storageBucket: 'linktab-3f36d.appspot.com',
  );
}
